# Generated by Django 4.2.5 on 2024-10-03 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crmAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duty',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmAdmin.employee'),
        ),
        migrations.AddField(
            model_name='duty',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmAdmin.lead'),
        ),
        migrations.AddField(
            model_name='callback',
            name='duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty', to='crmAdmin.duty'),
        ),
        migrations.AddField(
            model_name='admins',
            name='superadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
