# Generated by Django 4.2.5 on 2024-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmAdmin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
