# Generated by Django 4.2.5 on 2024-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmAdmin', '0004_won_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
