# Generated by Django 4.2.5 on 2024-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmAdmin', '0004_salereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereport',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
