# Generated by Django 4.2.5 on 2024-10-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmAdmin', '0005_callback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmAdmin.lead')),
            ],
        ),
    ]
