# Generated by Django 4.2.5 on 2024-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmAdmin', '0006_saleperson_total_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leeds',
            name='lead_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Won', 'Won'), ('NA', 'NA')], default='No', max_length=3),
        ),
    ]
