# Generated by Django 4.2.5 on 2024-10-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmAdmin', '0007_report_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='target',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admins',
            name='target_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='Notanswer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='Notinterested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='follow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
